import json

res = {
   "after":"d5d91603aa811a05119718bf4ea78964e696d86d",
   "base_ref":None,
   "before":"5691eaa5c470bafc5120b087138ca9bff05cfeac",
   "commits":[
      {
         "added":[
            
         ],
         "author":{
            "email":"syedshoeb886@gmail.com",
            "name":"Syed Shoeb",
            "username":"shoeb00"
         },
         "committer":{
            "email":"noreply@github.com",
            "name":"GitHub",
            "username":"web-flow"
         },
         "distinct":False,
         "id":"327ff1e5caf8d43b845e12645fe1c8052df3ed4b",
         "message":"Revert \"Revert \"Revert \"Add files via upload\"\"\"",
         "modified":[
            "test.py"
         ],
         "removed":[
            
         ],
         "timestamp":"2021-08-26T23:42:09+05:30",
         "tree_id":"c8a92873cad557a165c13fd44c6f6e8380f4bbe7",
         "url":"https://github.com/shoeb00/Test/commit/327ff1e5caf8d43b845e12645fe1c8052df3ed4b"
      },
      {
         "added":[
            
         ],
         "author":{
            "email":"syedshoeb886@gmail.com",
            "name":"Syed Shoeb",
            "username":"shoeb00"
         },
         "committer":{
            "email":"noreply@github.com",
            "name":"GitHub",
            "username":"web-flow"
         },
         "distinct":True,
         "id":"d5d91603aa811a05119718bf4ea78964e696d86d",
         "message":"Merge pull request #4 from shoeb00/revert-3-revert-2-revert-1-shoeb00-patch-1\n\nRevert \"Revert \"Revert \"Add files via upload\"\"\"",
         "modified":[
            "test.py"
         ],
         "removed":[
            
         ],
         "timestamp":"2021-08-26T23:47:00+05:30",
         "tree_id":"c8a92873cad557a165c13fd44c6f6e8380f4bbe7",
         "url":"https://github.com/shoeb00/Test/commit/d5d91603aa811a05119718bf4ea78964e696d86d"
      }
   ],
   "compare":"https://github.com/shoeb00/Test/compare/5691eaa5c470...d5d91603aa81",
   "created":False,
   "deleted":False,
   "forced":False,
   "head_commit":{
      "added":[
         
      ],
      "author":{
         "email":"syedshoeb886@gmail.com",
         "name":"Syed Shoeb",
         "username":"shoeb00"
      },
      "committer":{
         "email":"noreply@github.com",
         "name":"GitHub",
         "username":"web-flow"
      },
      "distinct":True,
      "id":"d5d91603aa811a05119718bf4ea78964e696d86d",
      "message":"Merge pull request #4 from shoeb00/revert-3-revert-2-revert-1-shoeb00-patch-1\n\nRevert \"Revert \"Revert \"Add files via upload\"\"\"",
      "modified":[
         "test.py"
      ],
      "removed":[
         
      ],
      "timestamp":"2021-08-26T23:47:00+05:30",
      "tree_id":"c8a92873cad557a165c13fd44c6f6e8380f4bbe7",
      "url":"https://github.com/shoeb00/Test/commit/d5d91603aa811a05119718bf4ea78964e696d86d"
   },
   "pusher":{
      "email":"syedshoeb886@gmail.com",
      "name":"shoeb00"
   },
   "ref":"refs/heads/master",
   "repository":{
      "archive_url":"https://api.github.com/repos/shoeb00/Test/{archive_format}{/ref}",
      "archived":False,
      "assignees_url":"https://api.github.com/repos/shoeb00/Test/assignees{/user}",
      "blobs_url":"https://api.github.com/repos/shoeb00/Test/git/blobs{/sha}",
      "branches_url":"https://api.github.com/repos/shoeb00/Test/branches{/branch}",
      "clone_url":"https://github.com/shoeb00/Test.git",
      "collaborators_url":"https://api.github.com/repos/shoeb00/Test/collaborators{/collaborator}",
      "comments_url":"https://api.github.com/repos/shoeb00/Test/comments{/number}",
      "commits_url":"https://api.github.com/repos/shoeb00/Test/commits{/sha}",
      "compare_url":"https://api.github.com/repos/shoeb00/Test/compare/{base}...{head}",
      "contents_url":"https://api.github.com/repos/shoeb00/Test/contents/{+path}",
      "contributors_url":"https://api.github.com/repos/shoeb00/Test/contributors",
      "created_at":1572594410,
      "default_branch":"master",
      "deployments_url":"https://api.github.com/repos/shoeb00/Test/deployments",
      "description":"Still learning",
      "disabled":False,
      "downloads_url":"https://api.github.com/repos/shoeb00/Test/downloads",
      "events_url":"https://api.github.com/repos/shoeb00/Test/events",
      "fork":False,
      "forks":0,
      "forks_count":0,
      "forks_url":"https://api.github.com/repos/shoeb00/Test/forks",
      "full_name":"shoeb00/Test",
      "git_commits_url":"https://api.github.com/repos/shoeb00/Test/git/commits{/sha}",
      "git_refs_url":"https://api.github.com/repos/shoeb00/Test/git/refs{/sha}",
      "git_tags_url":"https://api.github.com/repos/shoeb00/Test/git/tags{/sha}",
      "git_url":"git://github.com/shoeb00/Test.git",
      "has_downloads":True,
      "has_issues":True,
      "has_pages":False,
      "has_projects":True,
      "has_wiki":True,
      "homepage":None,
      "hooks_url":"https://api.github.com/repos/shoeb00/Test/hooks",
      "html_url":"https://github.com/shoeb00/Test",
      "id":218938071,
      "issue_comment_url":"https://api.github.com/repos/shoeb00/Test/issues/comments{/number}",
      "issue_events_url":"https://api.github.com/repos/shoeb00/Test/issues/events{/number}",
      "issues_url":"https://api.github.com/repos/shoeb00/Test/issues{/number}",
      "keys_url":"https://api.github.com/repos/shoeb00/Test/keys{/key_id}",
      "labels_url":"https://api.github.com/repos/shoeb00/Test/labels{/name}",
      "language":"Python",
      "languages_url":"https://api.github.com/repos/shoeb00/Test/languages",
      "license":None,
      "master_branch":"master",
      "merges_url":"https://api.github.com/repos/shoeb00/Test/merges",
      "milestones_url":"https://api.github.com/repos/shoeb00/Test/milestones{/number}",
      "mirror_url":None,
      "name":"Test",
      "node_id":"MDEwOlJlcG9zaXRvcnkyMTg5MzgwNzE=",
      "notifications_url":"https://api.github.com/repos/shoeb00/Test/notifications{?since,all,participating}",
      "open_issues":0,
      "open_issues_count":0,
      "owner":{
         "avatar_url":"https://avatars.githubusercontent.com/u/53873845?v=4",
         "email":"syedshoeb886@gmail.com",
         "events_url":"https://api.github.com/users/shoeb00/events{/privacy}",
         "followers_url":"https://api.github.com/users/shoeb00/followers",
         "following_url":"https://api.github.com/users/shoeb00/following{/other_user}",
         "gists_url":"https://api.github.com/users/shoeb00/gists{/gist_id}",
         "gravatar_id":"",
         "html_url":"https://github.com/shoeb00",
         "id":53873845,
         "login":"shoeb00",
         "name":"shoeb00",
         "node_id":"MDQ6VXNlcjUzODczODQ1",
         "organizations_url":"https://api.github.com/users/shoeb00/orgs",
         "received_events_url":"https://api.github.com/users/shoeb00/received_events",
         "repos_url":"https://api.github.com/users/shoeb00/repos",
         "site_admin":False,
         "starred_url":"https://api.github.com/users/shoeb00/starred{/owner}{/repo}",
         "subscriptions_url":"https://api.github.com/users/shoeb00/subscriptions",
         "type":"User",
         "url":"https://api.github.com/users/shoeb00"
      },
      "private":False,
      "pulls_url":"https://api.github.com/repos/shoeb00/Test/pulls{/number}",
      "pushed_at":1630001820,
      "releases_url":"https://api.github.com/repos/shoeb00/Test/releases{/id}",
      "size":4,
      "ssh_url":"git@github.com:shoeb00/Test.git",
      "stargazers":0,
      "stargazers_count":0,
      "stargazers_url":"https://api.github.com/repos/shoeb00/Test/stargazers",
      "statuses_url":"https://api.github.com/repos/shoeb00/Test/statuses/{sha}",
      "subscribers_url":"https://api.github.com/repos/shoeb00/Test/subscribers",
      "subscription_url":"https://api.github.com/repos/shoeb00/Test/subscription",
      "svn_url":"https://github.com/shoeb00/Test",
      "tags_url":"https://api.github.com/repos/shoeb00/Test/tags",
      "teams_url":"https://api.github.com/repos/shoeb00/Test/teams",
      "trees_url":"https://api.github.com/repos/shoeb00/Test/git/trees{/sha}",
      "updated_at":"2021-08-26T17:54:49Z",
      "url":"https://github.com/shoeb00/Test",
      "watchers":0,
      "watchers_count":0
   },
   "sender":{
      "avatar_url":"https://avatars.githubusercontent.com/u/53873845?v=4",
      "events_url":"https://api.github.com/users/shoeb00/events{/privacy}",
      "followers_url":"https://api.github.com/users/shoeb00/followers",
      "following_url":"https://api.github.com/users/shoeb00/following{/other_user}",
      "gists_url":"https://api.github.com/users/shoeb00/gists{/gist_id}",
      "gravatar_id":"",
      "html_url":"https://github.com/shoeb00",
      "id":53873845,
      "login":"shoeb00",
      "node_id":"MDQ6VXNlcjUzODczODQ1",
      "organizations_url":"https://api.github.com/users/shoeb00/orgs",
      "received_events_url":"https://api.github.com/users/shoeb00/received_events",
      "repos_url":"https://api.github.com/users/shoeb00/repos",
      "site_admin":False,
      "starred_url":"https://api.github.com/users/shoeb00/starred{/owner}{/repo}",
      "subscriptions_url":"https://api.github.com/users/shoeb00/subscriptions",
      "type":"User",
      "url":"https://api.github.com/users/shoeb00"
   }
}
print(res['commits'][0]['author'])